// app/pages/publishers/[name].vue
<template>
  <div v-if="user">
    <img
      :src="userBackground"
      class="object-cover w-full max-h-48 mb-8"
      style="aspect-ratio: 16/7"
    />

    <v-container>
      <div class="layout">
        <div class="main">
          <!-- Filter Section -->
          <v-card class="mb-4">
            <v-tabs
              v-model="activeCategoryTab"
              color="primary"
              class="mb-2"
              grow
            >
              <v-tab value="all">All</v-tab>
              <v-tab value="posts">Posts</v-tab>
              <v-tab value="articles">Articles</v-tab>
            </v-tabs>

            <v-row>
              <v-col cols="12" sm="6">
                <v-checkbox
                  :model-value="includeReplies"
                  label="Include replies"
                  :indeterminate="includeReplies === null"
                  density="compact"
                  prepend-icon="mdi-reply"
                  hide-details
                  class="px-4"
                  @update:model-value="cycleIncludeReplies"
                />
              </v-col>
              <v-col cols="12" sm="6">
                <v-checkbox
                  v-model="mediaOnly"
                  label="Media only"
                  density="compact"
                  hide-details
                  class="px-4"
                  prepend-icon="mdi-attachment"
                />
              </v-col>
            </v-row>

            <v-checkbox
              v-model="orderDesc"
              label="Descending order"
              density="compact"
              prepend-icon="mdi-sort"
              class="px-4"
              hide-details
            />

            <v-divider class="my-1" />

            <v-list-item
              title="Advanced filters"
              prepend-icon="mdi-filter-variant"
              @click="showAdvancedFilters = !showAdvancedFilters"
            >
              <template #append>
                <v-icon>
                  {{
                    showAdvancedFilters ? "mdi-chevron-up" : "mdi-chevron-down"
                  }}
                </v-icon>
              </template>
            </v-list-item>

            <v-expand-transition>
              <div v-if="showAdvancedFilters" class="my-3 px-4">
                <v-text-field
                  v-model="queryTerm"
                  hide-details
                  label="Search"
                  placeholder="Search posts"
                  prepend-inner-icon="mdi-magnify"
                  variant="outlined"
                  density="comfortable"
                  class="mb-3"
                />

                <v-select
                  v-model="order"
                  hide-details
                  label="Sort by"
                  :items="[
                    { title: 'Date', value: 'date' },
                    { title: 'Popularity', value: 'popularity' }
                  ]"
                  variant="outlined"
                  density="comfortable"
                  class="mb-3"
                />

                <v-row>
                  <v-col cols="12" sm="6">
                    <v-text-field
                      :model-value="periodStartFormatted"
                      hide-details
                      label="From date"
                      prepend-inner-icon="mdi-calendar"
                      variant="outlined"
                      density="comfortable"
                      readonly
                      @click="openDatePicker('start')"
                    />
                  </v-col>
                  <v-col cols="12" sm="6">
                    <v-text-field
                      :model-value="periodEndFormatted"
                      hide-details
                      label="To date"
                      prepend-inner-icon="mdi-calendar"
                      variant="outlined"
                      density="comfortable"
                      readonly
                      @click="openDatePicker('end')"
                    />
                  </v-col>
                </v-row>
              </div>
            </v-expand-transition>
          </v-card>

          <post-list :key="filterKey" :params="postListParams" />

          <!-- Date Picker Dialog -->
          <v-dialog v-model="datePickerDialog" max-width="400">
            <v-card>
              <v-card-title>{{
                datePickerType === "start" ? "From date" : "To date"
              }}</v-card-title>
              <v-card-text>
                <v-date-picker
                  v-model="tempDate"
                  :max="new Date().toISOString().split('T')[0]"
                />
              </v-card-text>
              <v-card-actions>
                <v-spacer />
                <v-btn @click="datePickerDialog = false">Cancel</v-btn>
                <v-btn color="primary" @click="confirmDatePicker">OK</v-btn>
              </v-card-actions>
            </v-card>
          </v-dialog>
        </div>
        <div class="sidebar flex flex-col gap-3">
          <v-card class="w-full">
            <v-card-text>
              <div class="flex items-center gap-4 mb-4">
                <v-avatar size="60" rounded="circle" :image="userPicture" />
                <div>
                  <div class="text-xl font-bold">
                    {{ user.nick || user.name }}
                  </div>
                  <div class="text-body-2 text-medium-emphasis">
                    @{{ user.name }}
                  </div>
                </div>
              </div>
              <div v-if="htmlBio" class="bio-prose" v-html="htmlBio"></div>
            </v-card-text>
          </v-card>
        </div>
      </div>
    </v-container>
  </div>
  <div v-else-if="notFound" class="flex justify-center items-center h-full">
    <v-empty-state
      icon="mdi-account-off"
      title="User not found"
      text="The user profile you're trying to access is not found."
    />
  </div>
  <div v-else class="flex justify-center items-center h-full">
    <v-progress-circular indeterminate size="64" color="primary" />
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from "vue"
import { useMarkdownProcessor } from "~/composables/useMarkdownProcessor"
import type { SnPublisher } from "~/types/api"
import type { PostListParams } from "~/composables/usePostList"

import PostList from "~/components/Post/PostList.vue"

const route = useRoute()

const notFound = ref<boolean>(false)
const user = ref<SnPublisher | null>(null)

const username = computed(() => {
  const nameStr = route.params.name?.toString()
  if (nameStr?.startsWith("@")) return nameStr.substring(1)
  return nameStr
})

// Use useFetch with the correct API URL to avoid router conflicts
const apiBase = useSolarNetworkUrl()
const apiBaseServer = useSolarNetworkUrl()

try {
  const { data, error } = await useFetch<SnPublisher>(
    `${apiBaseServer}/sphere/publishers/${username.value}`,
    { server: true }
  )

  if (error.value) {
    console.error("Failed to fetch user:", error.value)
    notFound.value = true
  } else if (data.value) {
    user.value = data.value
  }
} catch (err) {
  console.error("Failed to fetch user:", err)
  notFound.value = true
}

const { render } = useMarkdownProcessor()

const htmlBio = ref<string | undefined>(undefined)

watch(
  user,
  (value) => {
    htmlBio.value = value?.bio ? render(value.bio) : undefined
  },
  { immediate: true, deep: true }
)

const userBackground = computed(() => {
  return user.value?.background
    ? `${apiBase}/drive/files/${user.value.background.id}?original=true`
    : undefined
})
const userPicture = computed(() => {
  return user.value?.picture
    ? `${apiBase}/drive/files/${user.value.picture.id}`
    : undefined
})

// Filter state
const activeCategoryTab = ref("all")
const includeReplies = ref<boolean | null>(null)
const mediaOnly = ref(false)
const orderDesc = ref(true)
const showAdvancedFilters = ref(false)
const queryTerm = ref("")
const order = ref<string | undefined>(undefined)
const periodStart = ref<number | undefined>(undefined)
const periodEnd = ref<number | undefined>(undefined)

// Date picker dialog
const datePickerDialog = ref(false)
const datePickerType = ref<"start" | "end">("start")
const tempDate = ref<Date | undefined>(undefined)

const postListParams = computed<PostListParams>(() => {
  const params: PostListParams = {
    pubName: username.value,
    includeReplies: includeReplies.value ?? undefined,
    mediaOnly: mediaOnly.value,
    orderDesc: orderDesc.value,
    queryTerm: queryTerm.value || undefined,
    order: order.value,
    periodStart: periodStart.value,
    periodEnd: periodEnd.value
  }

  // Set type based on active tab
  if (activeCategoryTab.value === "posts") {
    params.type = 0 // Assuming 0 is for posts
  } else if (activeCategoryTab.value === "articles") {
    params.type = 1 // Assuming 1 is for articles
  }
  // 'all' means no type filter

  return params
})

const periodStartFormatted = computed(() => {
  return periodStart.value
    ? new Date(periodStart.value * 1000).toISOString().split("T")[0]
    : ""
})

const periodEndFormatted = computed(() => {
  return periodEnd.value
    ? new Date(periodEnd.value * 1000).toISOString().split("T")[0]
    : ""
})

// Create a key that changes when filters change to force PostList re-mount
const filterKey = computed(() => {
  return JSON.stringify(postListParams.value)
})

const cycleIncludeReplies = () => {
  if (includeReplies.value === null) {
    includeReplies.value = false
  } else if (includeReplies.value === false) {
    includeReplies.value = true
  } else {
    includeReplies.value = null
  }
}

const openDatePicker = (type: "start" | "end") => {
  datePickerType.value = type
  tempDate.value =
    type === "start"
      ? periodStart.value
        ? new Date(periodStart.value * 1000)
        : new Date()
      : periodEnd.value
      ? new Date(periodEnd.value * 1000)
      : new Date()
  datePickerDialog.value = true
}

const confirmDatePicker = () => {
  if (tempDate.value) {
    const timestamp = Math.floor(tempDate.value.getTime() / 1000)
    if (datePickerType.value === "start") {
      periodStart.value = timestamp
    } else {
      periodEnd.value = timestamp
    }
  }
  datePickerDialog.value = false
}

definePageMeta({
  alias: ["/p/:name()"]
})

useHead({
  title: computed(() => {
    if (notFound.value) {
      return "User not found"
    }
    if (user.value) {
      return user.value.nick || user.value.name
    }
    return "Loading user..."
  }),
  meta: computed(() => {
    if (user.value) {
      const description = `View the profile of ${
        user.value.nick || user.value.name
      } on Solar Network.`
      return [{ name: "description", content: description }]
    }
    return []
  })
})

defineOgImage({
  component: "ImageCard",
  title: computed(() =>
    user.value ? user.value.nick || user.value.name : "Publisher Profile"
  ),
  description: computed(() =>
    user.value
      ? `View the profile of ${
          user.value.nick || user.value.name
        } on Solar Network.`
      : ""
  ),
  avatarUrl: computed(() => userPicture.value),
  backgroundImage: computed(() => userBackground.value)
})
</script>

<style scoped>
.bio-prose img {
  display: inline !important;
  margin: 0 !important;
}

.layout {
  display: grid;
  grid-template-columns: 1fr;
  gap: 16px;
}

.main {
  order: 2;
  min-width: 0;
}

.sidebar {
  order: 1;
  overflow-y: auto;
  height: auto;
  max-height: 100vh;
}

@media (min-width: 960px) {
  .layout {
    grid-template-columns: 2fr 1fr;
  }

  .main {
    order: unset;
  }

  .sidebar {
    order: unset;
  }
}

@media (min-width: 1280px) {
  .sidebar {
    position: sticky;
    top: calc(68px + 8px);
  }
}
</style>

// src/routes/(app)/publishers/[name]/+page.svelte
<script lang="ts">
	import PostCard from '$lib/components/PostCard.svelte';
	import { getFileUrl } from '$lib/utils/files';
	import { renderMarkdown } from '$lib/utils/markdown';
	import { Search, Image, MessageCircle, ArrowDownUp, ShieldCheck, UserX, Loader2 } from 'lucide-svelte';
	import type { PageData } from './$types';
	import type { Post } from '$lib/types/post';

	let { data }: { data: PageData } = $props();

	let initialized = $state(false);
	let posts = $state<Post[]>([]);
	let error = $state<string | null>(null);
	let isLoading = $state(false);
	let isRefreshing = $state(false);
	let total = $state(0);
	let offset = $state(0);
	let hasMore = $state(false);

	let contentType = $state<'all' | 'posts' | 'articles'>('all');
	let includeReplies = $state<boolean | null>(null);
	let mediaOnly = $state(false);
	let orderDesc = $state(true);
	let query = $state('');

	$effect(() => {
		if (initialized) return;
		posts = data.posts;
		error = data.error;
		total = data.total || data.posts.length;
		offset = data.posts.length;
		hasMore = data.posts.length >= data.initialTake && data.posts.length < total;
		initialized = true;
	});

	const publisher = $derived(data.publisher);
	const displayName = $derived(publisher?.nick || publisher?.name || 'Unknown');
	const avatarUrl = $derived(getFileUrl(publisher?.picture?.id));
	const backgroundUrl = $derived(getFileUrl(publisher?.background?.id));
	const bioHtml = $derived(publisher?.bio ? renderMarkdown(publisher.bio) : '');
	const publisherRouteName = $derived(encodeURIComponent(publisher?.name || ''));

	function getInitials(name: string): string {
		return name
			.split(/\s+/)
			.filter(Boolean)
			.map((part) => part[0]?.toUpperCase())
			.slice(0, 2)
			.join('') || '?';
	}

	function cycleRepliesFilter() {
		if (includeReplies === null) includeReplies = true;
		else if (includeReplies === true) includeReplies = false;
		else includeReplies = null;
	}

	function buildFilterParams(currentOffset: number): URLSearchParams {
		const params = new URLSearchParams({
			offset: String(currentOffset),
			take: String(data.initialTake),
			orderDesc: String(orderDesc)
		});

		if (contentType === 'posts') params.set('type', '0');
		if (contentType === 'articles') params.set('type', '1');
		if (includeReplies !== null) params.set('replies', String(includeReplies));
		if (mediaOnly) params.set('media', 'true');
		if (query.trim()) params.set('query', query.trim());

		return params;
	}

	async function reloadWithFilters() {
		if (!publisherRouteName) return;
		isLoading = true;
		isRefreshing = true;
		error = null;
		try {
			const params = buildFilterParams(0);
			const response = await fetch(`/api/publishers/${publisherRouteName}/posts?${params.toString()}`, {
				cache: 'no-store'
			});
			const result = await response.json();
			if (!response.ok) throw new Error(result.error || 'Failed to fetch posts');

			posts = result.posts || [];
			total = result.total || posts.length;
			offset = posts.length;
			hasMore = posts.length >= data.initialTake && posts.length < total;
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to load posts';
		} finally {
			isLoading = false;
			isRefreshing = false;
		}
	}

	async function loadMore() {
		if (!hasMore || isLoading || !publisherRouteName) return;
		isLoading = true;
		error = null;
		try {
			const params = buildFilterParams(offset);
			const response = await fetch(`/api/publishers/${publisherRouteName}/posts?${params.toString()}`, {
				cache: 'no-store'
			});
			const result = await response.json();
			if (!response.ok) throw new Error(result.error || 'Failed to fetch posts');

			const more: Post[] = result.posts || [];
			posts = [...posts, ...more];
			offset += more.length;
			total = result.total || total;
			hasMore = posts.length < total && more.length > 0;
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to load more posts';
		} finally {
			isLoading = false;
		}
	}
</script>

<svelte:head>
	<title>{displayName} | Solar Network</title>
</svelte:head>

{#if data.notFound}
	<div class="mx-auto max-w-2xl p-6">
		<div class="card border border-base-300 bg-base-100">
			<div class="card-body items-center text-center">
				<UserX class="text-base-content/50" size={40} />
				<h1 class="text-xl font-bold">Publisher not found</h1>
				<p class="text-base-content/60">The profile you requested does not exist.</p>
			</div>
		</div>
	</div>
{:else if !publisher}
	<div class="mx-auto max-w-2xl p-6">
		<div class="alert alert-error"><span>{data.error || 'Failed to load publisher profile'}</span></div>
	</div>
{:else}
	<div class="mx-auto max-w-5xl">
		<section class="relative overflow-hidden border-b border-base-300">
			<div class="h-40 w-full bg-base-200 sm:h-52">
				{#if backgroundUrl}
					<img src={backgroundUrl} alt={`${displayName} background`} class="h-full w-full object-cover" />
				{/if}
			</div>
			<div class="mx-auto -mt-16 flex max-w-5xl flex-col gap-4 px-4 pb-4 sm:-mt-14 sm:flex-row sm:items-end sm:px-6">
				<div class="shrink-0">
					{#if avatarUrl}
						<div class="avatar">
							<div class="h-24 w-24 rounded-3xl ring ring-base-300 ring-offset-2 ring-offset-base-100 sm:h-28 sm:w-28">
								<img src={avatarUrl} alt={displayName} />
							</div>
						</div>
					{:else}
						<div class="avatar avatar-placeholder">
							<div class="h-24 w-24 rounded-3xl bg-primary text-primary-content ring ring-base-300 ring-offset-2 ring-offset-base-100 sm:h-28 sm:w-28">
								<span class="text-2xl font-semibold">{getInitials(displayName)}</span>
							</div>
						</div>
					{/if}
				</div>
				<div class="min-w-0 flex-1">
					<div class="flex flex-wrap items-center gap-2 pt-18">
						<h1 class="truncate text-2xl font-black sm:text-3xl">{displayName}</h1>
						{#if publisher.verification}
							<span class="badge badge-primary gap-1">
								<ShieldCheck size={12} />
								Verified
							</span>
						{/if}
					</div>
					<p class="truncate text-sm text-base-content/60">@{publisher.name}</p>
				</div>
				<div class="flex gap-3 text-sm">
					<div class="rounded-xl border border-base-300 bg-base-100 px-3 py-2">
						<div class="font-semibold">{total}</div>
						<div class="text-base-content/60">Posts</div>
					</div>
				</div>
			</div>
		</section>

		<div class="space-y-4 px-4 py-4 lg:px-6">
			<section class="space-y-4">
				<div class="card border border-base-300 bg-base-100">
					<div class="card-body p-4">
						<h2 class="text-sm font-semibold text-base-content/70">Bio</h2>
						{#if bioHtml}
							<article class="prose prose-sm max-w-none">{@html bioHtml}</article>
						{:else}
							<p class="text-sm text-base-content/60">No bio yet.</p>
						{/if}
					</div>
				</div>
				{#if publisher.verification}
					<div class="card border border-base-300 bg-base-100">
						<div class="card-body p-4">
							<p class="text-sm font-semibold">{publisher.verification.title || 'Verified account'}</p>
							{#if publisher.verification.description}
								<p class="text-sm text-base-content/70">{publisher.verification.description}</p>
							{/if}
							{#if publisher.verification.verified_by}
								<p class="text-xs text-base-content/60">By {publisher.verification.verified_by}</p>
							{/if}
						</div>
					</div>
				{/if}
			</section>

			<section class="space-y-4">
				<div class="card border border-base-300 bg-base-100">
					<div class="card-body gap-4 p-4">
						{#if isRefreshing}
							<div class="mb-1 flex items-center gap-2 text-sm text-base-content/60">
								<Loader2 class="animate-spin" size={14} />
								Refreshing feed...
							</div>
						{/if}
						<div class="join w-full">
							<button class="flex-1 btn join-item {contentType === 'all' ? 'btn-primary' : 'border-base-300 bg-base-100 text-base-content hover:bg-base-200'}" onclick={() => { contentType = 'all'; reloadWithFilters(); }}>All</button>
							<button class="flex-1 btn join-item {contentType === 'posts' ? 'btn-primary' : 'border-base-300 bg-base-100 text-base-content hover:bg-base-200'}" onclick={() => { contentType = 'posts'; reloadWithFilters(); }}>Posts</button>
							<button class="flex-1 btn join-item {contentType === 'articles' ? 'btn-primary' : 'border-base-300 bg-base-100 text-base-content hover:bg-base-200'}" onclick={() => { contentType = 'articles'; reloadWithFilters(); }}>Articles</button>
						</div>
						<div class="grid gap-2 sm:grid-cols-2">
							<button class="btn justify-start border-base-300 bg-base-100 text-base-content hover:bg-base-200" onclick={() => { cycleRepliesFilter(); reloadWithFilters(); }}>
								<MessageCircle size={14} />
								Replies:
								{includeReplies === null ? 'Auto' : includeReplies ? 'On' : 'Off'}
							</button>
							<button class="btn justify-start border-base-300 bg-base-100 text-base-content hover:bg-base-200" onclick={() => { mediaOnly = !mediaOnly; reloadWithFilters(); }}>
								<Image size={14} />
								Media only: {mediaOnly ? 'On' : 'Off'}
							</button>
							<button class="btn justify-start border-base-300 bg-base-100 text-base-content hover:bg-base-200" onclick={() => { orderDesc = !orderDesc; reloadWithFilters(); }}>
								<ArrowDownUp size={14} />
								Order: {orderDesc ? 'Newest' : 'Oldest'}
							</button>
							<div class="join">
								<input
									class="input input-bordered join-item w-full"
									placeholder="Search posts"
									bind:value={query}
									onkeydown={(e) => e.key === 'Enter' && reloadWithFilters()}
								/>
								<button class="btn btn-primary join-item" onclick={reloadWithFilters}><Search size={14} /></button>
							</div>
						</div>
					</div>
				</div>

				{#if error}
					<div class="alert alert-error"><span>{error}</span></div>
				{/if}

				{#if posts.length > 0}
					<div class="space-y-4 transition-opacity duration-200 {isRefreshing ? 'opacity-60' : 'opacity-100'}">
						{#each posts as post (post.id)}
							<PostCard {post} />
						{/each}
					</div>
					<div class="py-2 text-center">
						{#if hasMore}
							<button class="btn btn-outline" onclick={loadMore} disabled={isLoading}>
								{#if isLoading}
									<Loader2 class="animate-spin" size={16} />
								{/if}
								Load more
							</button>
						{:else}
							<p class="text-sm text-base-content/50">No more posts</p>
						{/if}
					</div>
				{:else if !error}
					<div class="rounded-xl border border-base-300 bg-base-100 p-8 text-center text-base-content/60">
						No posts for this publisher with current filters.
					</div>
				{/if}
			</section>
		</div>
	</div>
{/if}
