// src/routes/(auth)/auth/authorize/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { Check, Plug, X } from 'lucide-svelte';
	import { getAuthorizeClientInfo, submitAuthorizeDecision } from '$lib/utils/api';
	import { getFileUrl } from '$lib/utils/files';

	interface ClientInfo {
		clientName?: string;
		homeUri?: string;
		picture?: { id?: string };
		background?: { id?: string };
		scopes?: string[];
	}

	let isLoading = $state(true);
	let isAuthorizing = $state(false);
	let error = $state('');
	let clientInfo = $state<ClientInfo | null>(null);

	const backgroundUrl = $derived(getFileUrl(clientInfo?.background?.id));
	const avatarUrl = $derived(getFileUrl(clientInfo?.picture?.id));
	const requestedScopes = $derived(clientInfo?.scopes || []);

	onMount(async () => {
		try {
			const query = new URLSearchParams(window.location.search);
			clientInfo = await getAuthorizeClientInfo(query);
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to load app authorization request';
		} finally {
			isLoading = false;
		}
	});

	async function handleAuthorize(authorize: boolean) {
		isAuthorizing = true;
		error = '';
		try {
			const query = new URLSearchParams(window.location.search);
			const result = await submitAuthorizeDecision(query, authorize);
			if (result.redirectUri) {
				window.location.href = result.redirectUri;
			}
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to submit authorization decision';
		} finally {
			isAuthorizing = false;
		}
	}
</script>

<svelte:head>
	<title>Authorize Application - Floating Island</title>
</svelte:head>

{#if backgroundUrl}
	<div class="fixed inset-0 -z-10 bg-cover bg-center opacity-30 blur-sm" style={`background-image: url('${backgroundUrl}')`}></div>
{/if}

<div class="w-full max-w-2xl rounded-3xl border border-base-300/70 bg-base-100/85 p-6 shadow-2xl backdrop-blur-xl md:p-8">
	{#if isLoading}
		<div class="flex items-center justify-center py-16">
			<span class="loading loading-spinner loading-lg text-primary"></span>
		</div>
	{:else}
		<div class="mb-6 flex items-center gap-4">
			{#if avatarUrl}
				<div class="avatar">
					<div class="w-14 rounded-2xl">
						<img src={avatarUrl} alt="Client app icon" />
					</div>
				</div>
			{:else}
				<div class="avatar avatar-placeholder">
					<div class="h-14 w-14 rounded-2xl bg-primary/15 text-primary"><Plug size={24} /></div>
				</div>
			{/if}
			<div class="min-w-0">
				<h1 class="truncate text-2xl font-black">{clientInfo?.clientName || 'Unknown Application'}</h1>
				<p class="truncate text-sm text-base-content/70">wants access to your Solar Network account</p>
			</div>
		</div>

		{#if error}
			<div class="alert alert-error mb-4"><span>{error}</span></div>
		{/if}

		<div class="rounded-2xl border border-base-300 bg-base-200/60 p-4">
			<p class="mb-3 text-sm font-semibold">Requested permissions</p>
			{#if requestedScopes.length > 0}
				<ul class="space-y-2 text-sm">
					{#each requestedScopes as scope}
						<li class="flex items-start gap-2">
							<Check size={16} class="mt-0.5 text-success" />
							<span>{scope}</span>
						</li>
					{/each}
				</ul>
			{:else}
				<p class="text-sm text-base-content/60">No explicit scopes provided.</p>
			{/if}
		</div>

		<div class="mt-6 grid grid-cols-2 gap-3">
			<button class="btn btn-primary" onclick={() => handleAuthorize(true)} disabled={isAuthorizing}>
				{#if isAuthorizing}
					<span class="loading loading-spinner loading-sm"></span>
				{:else}
					<Check size={16} />
				{/if}
				Authorize
			</button>
			<button class="btn btn-outline" onclick={() => handleAuthorize(false)} disabled={isAuthorizing}>
				<X size={16} />
				Deny
			</button>
		</div>
	{/if}
</div>

// app/pages/auth/authorize.vue
<template>
  <v-container class="d-flex align-center justify-center fill-height">
    <v-card max-width="1000" rounded="lg" width="100%">
      <div v-if="isLoading" class="d-flex justify-center mb-4">
        <v-progress-linear indeterminate color="primary" height="4" />
      </div>
      <div class="pa-8">
        <div class="mb-4">
          <img
            :src="colorMode.value == 'dark' ? IconDark : IconLight"
            alt="CloudyLamb"
            height="60"
            width="60"
          />
        </div>
        <v-row>
          <v-col cols="12" lg="6" class="d-flex align-start justify-start">
            <div class="md:text-left h-auto">
              <h2 class="text-2xl font-bold mb-1">Authorize Application</h2>
              <p class="text-lg">Grant access to your Solar Network account</p>
            </div>
          </v-col>
          <v-col cols="12" lg="6" class="d-flex align-center justify-stretch">
            <div class="w-full d-flex flex-column md:text-right">
              <div v-if="error" class="mb-4">
                <v-alert
                  type="error"
                  closable
                  @update:model-value="error = null"
                >
                  {{ error }}
                </v-alert>
              </div>

              <!-- App Info Section -->
              <div v-if="clientInfo" class="mb-6">
                <div class="d-flex align-center mb-4 text-left">
                  <div>
                    <h3 class="text-xl font-semibold">
                      {{ clientInfo.clientName || "Unknown Application" }}
                    </h3>
                    <p class="text-base">
                      {{
                        isNewApp
                          ? "wants to access your Solar Network account"
                          : "wants to access your account"
                      }}
                    </p>
                  </div>
                </div>

                <!-- Requested Permissions -->
                <v-card variant="outlined" class="pa-4 mb-4 text-left">
                  <h4 class="font-medium mb-2">
                    This will allow
                    {{ clientInfo.clientName || "the app" }} to
                  </h4>
                  <ul class="space-y-1">
                    <li
                      v-for="scope in requestedScopes"
                      :key="scope"
                      class="d-flex align-start"
                    >
                      <v-icon class="mt-1 mr-2" color="success" size="18"
                        >mdi-check</v-icon
                      >
                      <span>{{ scope }}</span>
                    </li>
                  </ul>
                </v-card>

                <!-- Buttons -->
                <div class="d-flex gap-3 mt-4">
                  <v-btn
                    color="primary"
                    :loading="isAuthorizing"
                    class="flex-grow-1"
                    size="large"
                    @click="handleAuthorize"
                  >
                    Authorize
                  </v-btn>
                  <v-btn
                    variant="outlined"
                    :disabled="isAuthorizing"
                    class="flex-grow-1"
                    size="large"
                    @click="handleDeny"
                  >
                    Deny
                  </v-btn>
                </div>
              </div>
            </div>
          </v-col>
        </v-row>
      </div>
    </v-card>
    <footer-compact />
  </v-container>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from "vue"
import { useRoute } from "vue-router"
import { useSolarNetwork } from "~/composables/useSolarNetwork"

import IconLight from "~/assets/images/cloudy-lamb.png"
import IconDark from "~/assets/images/cloudy-lamb@dark.png"

const colorMode = useColorMode()

const route = useRoute()
const api = useSolarNetwork()

useHead({
  title: "Authorize Application"
})

// State
const isLoading = ref(true)
const isAuthorizing = ref(false)
const error = ref<string | null>(null)
const clientInfo = ref<{
  clientName?: string
  homeUri?: string
  picture?: { url: string }
  scopes?: string[]
} | null>(null)
const isNewApp = ref(false)

// Computed properties
const requestedScopes = computed(() => {
  return clientInfo.value?.scopes || []
})

// Methods
async function fetchClientInfo() {
  try {
    const queryString = window.location.search.slice(1)
    clientInfo.value = await api(`/id/auth/open/authorize?${queryString}`)
    checkIfNewApp()
  } catch (err) {
    error.value =
      (err instanceof Error ? err.message : String(err)) ||
      "An error occurred while loading the authorization request"
  } finally {
    isLoading.value = false
  }
}

function checkIfNewApp() {
  // In a real app, you might want to check if this is the first time authorizing this app
  // For now, we'll just set it to false
  isNewApp.value = false
}

async function handleAuthorize(authorize = true) {
  isAuthorizing.value = true
  try {
    const data = await api<{ redirectUri?: string }>(
      "/id/auth/open/authorize",
      {
        method: "POST",
        body: new URLSearchParams({
          ...route.query,
          authorize: authorize ? "true" : "false"
        })
      }
    )

    if (data.redirectUri) {
      window.location.href = data.redirectUri
    }
  } catch (err) {
    error.value =
      (err instanceof Error ? err.message : String(err)) ||
      "An error occurred during authorization"
  } finally {
    isAuthorizing.value = false
  }
}

function handleDeny() {
  handleAuthorize(false)
}

// Lifecycle
onMounted(() => {
  fetchClientInfo()
})

definePageMeta({
  middleware: "auth"
})
</script>

<style scoped>
/* Add any custom styles here */
</style>
