// src/routes/(app)/realms/[slug]/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import PostCard from '$lib/components/PostCard.svelte';
	import { getFileUrl } from '$lib/utils/files';
	import { apiClient } from '$lib/utils/api';
	import {
		Search,
		Image,
		MessageCircle,
		ArrowDownUp,
		ShieldCheck,
		Loader2,
		Users,
		UserPlus,
		Building2,
		Globe2,
		Lock
	} from 'lucide-svelte';
	import type { PageData } from './$types';
	import type { Post } from '$lib/types/post';

	let { data }: { data: PageData } = $props();

	let initialized = $state(false);
	let posts = $state<Post[]>([]);
	let error = $state<string | null>(null);
	let isLoading = $state(false);
	let isRefreshing = $state(false);
	let total = $state(0);
	let offset = $state(0);
	let hasMore = $state(false);

	let contentType = $state<'all' | 'posts' | 'articles'>('all');
	let includeReplies = $state<boolean | null>(null);
	let mediaOnly = $state(false);
	let orderDesc = $state(true);
	let query = $state('');

	let isJoining = $state(false);
	let isMember = $state(false);

	$effect(() => {
		if (initialized) return;
		posts = data.posts;
		error = data.error;
		total = data.total || data.posts.length;
		offset = data.posts.length;
		hasMore = data.posts.length >= data.initialTake && data.posts.length < total;
		initialized = true;
		checkMembership();
	});

	const realm = $derived(data.realm);
	const displayName = $derived(realm?.name || 'Unknown Realm');
	const avatarUrl = $derived(getFileUrl(realm?.picture?.id));
	const backgroundUrl = $derived(getFileUrl(realm?.background?.id));
	const realmRouteSlug = $derived(encodeURIComponent(realm?.slug || $page.params.slug || ''));

	function getInitials(name: string): string {
		return (
			name
				.split(/\s+/)
				.filter(Boolean)
				.map((part) => part[0]?.toUpperCase())
				.slice(0, 2)
				.join('') || '?'
		);
	}

	function cycleRepliesFilter() {
		if (includeReplies === null) includeReplies = true;
		else if (includeReplies === true) includeReplies = false;
		else includeReplies = null;
	}

	function buildFilterParams(currentOffset: number): URLSearchParams {
		const params = new URLSearchParams({
			offset: String(currentOffset),
			take: String(data.initialTake),
			orderDesc: String(orderDesc)
		});

		if (contentType === 'posts') params.set('type', '0');
		if (contentType === 'articles') params.set('type', '1');
		if (includeReplies !== null) params.set('replies', String(includeReplies));
		if (mediaOnly) params.set('media', 'true');
		if (query.trim()) params.set('query', query.trim());

		return params;
	}

	async function reloadWithFilters() {
		if (!realmRouteSlug) return;
		isLoading = true;
		isRefreshing = true;
		error = null;
		try {
			const params = buildFilterParams(0);
			const response = await fetch(`/api/realms/${realmRouteSlug}/posts?${params.toString()}`, {
				cache: 'no-store'
			});
			const result = await response.json();
			if (!response.ok) throw new Error(result.error || 'Failed to fetch posts');

			posts = result.posts || [];
			total = result.total || posts.length;
			offset = posts.length;
			hasMore = posts.length >= data.initialTake && posts.length < total;
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to load posts';
		} finally {
			isLoading = false;
			isRefreshing = false;
		}
	}

	async function loadMore() {
		if (!hasMore || isLoading || !realmRouteSlug) return;
		isLoading = true;
		error = null;
		try {
			const params = buildFilterParams(offset);
			const response = await fetch(`/api/realms/${realmRouteSlug}/posts?${params.toString()}`, {
				cache: 'no-store'
			});
			const result = await response.json();
			if (!response.ok) throw new Error(result.error || 'Failed to fetch posts');

			const more: Post[] = result.posts || [];
			posts = [...posts, ...more];
			offset += more.length;
			total = result.total || total;
			hasMore = posts.length < total && more.length > 0;
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to load more posts';
		} finally {
			isLoading = false;
		}
	}

	async function checkMembership() {
		if (!realm?.slug) return;
		try {
			await apiClient(`/pass/realms/${encodeURIComponent(realm.slug)}/members/me`);
			isMember = true;
		} catch {
			isMember = false;
		}
	}

	async function handleJoin() {
		if (!realm?.slug || isJoining || isMember) return;
		isJoining = true;
		try {
			await apiClient(`/pass/realms/${encodeURIComponent(realm.slug)}/members/me`, { method: 'POST' });
			isMember = true;
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to join realm';
		} finally {
			isJoining = false;
		}
	}
</script>

<svelte:head>
	<title>{displayName} | Solar Network</title>
</svelte:head>

{#if data.notFound}
	<div class="mx-auto max-w-2xl p-6">
		<div class="card border border-base-300 bg-base-100">
			<div class="card-body items-center text-center">
				<Users class="text-base-content/50" size={40} />
				<h1 class="text-xl font-bold">Realm not found</h1>
				<p class="text-base-content/60">The realm you requested does not exist.</p>
			</div>
		</div>
	</div>
{:else if !realm}
	<div class="mx-auto max-w-2xl p-6">
		<div class="alert alert-error"><span>{data.error || 'Failed to load realm'}</span></div>
	</div>
{:else}
	<div class="mx-auto max-w-5xl">
		<section class="relative overflow-hidden border-b border-base-300">
			<div class="h-40 w-full bg-base-200 sm:h-52">
				{#if backgroundUrl}
					<img src={backgroundUrl} alt={`${displayName} background`} class="h-full w-full object-cover" />
				{/if}
			</div>
			<div class="mx-auto -mt-16 flex max-w-5xl flex-col gap-4 px-4 pb-4 sm:-mt-14 sm:flex-row sm:items-end sm:px-6">
				<div class="shrink-0">
					{#if avatarUrl}
						<div class="avatar">
							<div class="h-24 w-24 rounded-3xl ring ring-base-300 ring-offset-2 ring-offset-base-100 sm:h-28 sm:w-28">
								<img src={avatarUrl} alt={displayName} />
							</div>
						</div>
					{:else}
						<div class="avatar avatar-placeholder">
							<div class="h-24 w-24 rounded-3xl bg-primary text-primary-content ring ring-base-300 ring-offset-2 ring-offset-base-100 sm:h-28 sm:w-28">
								<span class="text-2xl font-semibold">{getInitials(displayName)}</span>
							</div>
						</div>
					{/if}
				</div>
				<div class="min-w-0 flex-1">
					<div class="flex flex-wrap items-center gap-2 pt-18">
						<h1 class="truncate text-2xl font-black sm:text-3xl">{displayName}</h1>
						{#if realm.verification}
							<span class="badge badge-primary gap-1">
								<ShieldCheck size={12} />
								Verified
							</span>
						{/if}
					</div>
					<p class="truncate text-sm text-base-content/60">@{realm.slug}</p>
				</div>
				<div class="flex gap-3 text-sm">
					<div class="rounded-xl border border-base-300 bg-base-100 px-3 py-2">
						<div class="font-semibold">{total}</div>
						<div class="text-base-content/60">Posts</div>
					</div>
				</div>
			</div>
		</section>

		<div class="space-y-4 px-4 py-4 lg:px-6">
			<section class="space-y-4">
				<div class="card border border-base-300 bg-base-100">
					<div class="card-body p-4">
						{#if realm.description}
							<p class="text-sm text-base-content/80">{realm.description}</p>
						{:else}
							<p class="text-sm text-base-content/60">No description yet.</p>
						{/if}
						<div class="flex flex-wrap gap-2 pt-1">
							<span class="badge gap-1 border-info/30 bg-info/15 text-info">
								{#if realm.is_community}
									<Users size={12} />
									Community
								{:else}
									<Building2 size={12} />
									Organization
								{/if}
							</span>
							<span class="badge gap-1 {realm.is_public ? 'border-success/30 bg-success/15 text-success' : 'border-warning/30 bg-warning/20 text-warning'}">
								{#if realm.is_public}
									<Globe2 size={12} />
									Public
								{:else}
									<Lock size={12} />
									Private
								{/if}
							</span>
						</div>
					</div>
				</div>

				{#if realm.verification}
					<div class="card border border-base-300 bg-base-100">
						<div class="card-body p-4">
							<p class="text-sm font-semibold">{realm.verification.title || 'Verified realm'}</p>
							{#if realm.verification.description}
								<p class="text-sm text-base-content/70">{realm.verification.description}</p>
							{/if}
							{#if realm.verification.verified_by}
								<p class="text-xs text-base-content/60">By {realm.verification.verified_by}</p>
							{/if}
						</div>
					</div>
				{/if}

				{#if realm.is_public && !isMember}
					<button class="btn btn-primary w-full sm:w-auto" onclick={handleJoin} disabled={isJoining}>
						{#if isJoining}
							<Loader2 class="animate-spin" size={16} />
						{:else}
							<UserPlus size={16} />
						{/if}
						Join Realm
					</button>
				{/if}
			</section>

			<section class="space-y-4">
				<div class="card border border-base-300 bg-base-100">
					<div class="card-body gap-4 p-4">
						{#if isRefreshing}
							<div class="mb-1 flex items-center gap-2 text-sm text-base-content/60">
								<Loader2 class="animate-spin" size={14} />
								Refreshing feed...
							</div>
						{/if}
						<div class="join w-full">
							<button class="flex-1 btn join-item {contentType === 'all' ? 'btn-primary' : 'border-base-300 bg-base-100 text-base-content hover:bg-base-200'}" onclick={() => { contentType = 'all'; reloadWithFilters(); }}>All</button>
							<button class="flex-1 btn join-item {contentType === 'posts' ? 'btn-primary' : 'border-base-300 bg-base-100 text-base-content hover:bg-base-200'}" onclick={() => { contentType = 'posts'; reloadWithFilters(); }}>Posts</button>
							<button class="flex-1 btn join-item {contentType === 'articles' ? 'btn-primary' : 'border-base-300 bg-base-100 text-base-content hover:bg-base-200'}" onclick={() => { contentType = 'articles'; reloadWithFilters(); }}>Articles</button>
						</div>
						<div class="grid gap-2 sm:grid-cols-2">
							<button class="btn justify-start border-base-300 bg-base-100 text-base-content hover:bg-base-200" onclick={() => { cycleRepliesFilter(); reloadWithFilters(); }}>
								<MessageCircle size={14} />
								Replies:
								{includeReplies === null ? 'Auto' : includeReplies ? 'On' : 'Off'}
							</button>
							<button class="btn justify-start border-base-300 bg-base-100 text-base-content hover:bg-base-200" onclick={() => { mediaOnly = !mediaOnly; reloadWithFilters(); }}>
								<Image size={14} />
								Media only: {mediaOnly ? 'On' : 'Off'}
							</button>
							<button class="btn justify-start border-base-300 bg-base-100 text-base-content hover:bg-base-200" onclick={() => { orderDesc = !orderDesc; reloadWithFilters(); }}>
								<ArrowDownUp size={14} />
								Order: {orderDesc ? 'Newest' : 'Oldest'}
							</button>
							<div class="join">
								<input
									class="input input-bordered join-item w-full"
									placeholder="Search posts"
									bind:value={query}
									onkeydown={(e) => e.key === 'Enter' && reloadWithFilters()}
								/>
								<button class="btn btn-primary join-item" onclick={reloadWithFilters}><Search size={14} /></button>
							</div>
						</div>
					</div>
				</div>

				{#if error}
					<div class="alert alert-error"><span>{error}</span></div>
				{/if}

				{#if posts.length > 0}
					<div class="space-y-4 transition-opacity duration-200 {isRefreshing ? 'opacity-60' : 'opacity-100'}">
						{#each posts as post (post.id)}
							<PostCard {post} />
						{/each}
					</div>
					<div class="py-2 text-center">
						{#if hasMore}
							<button class="btn btn-outline" onclick={loadMore} disabled={isLoading}>
								{#if isLoading}
									<Loader2 class="animate-spin" size={16} />
								{/if}
								Load more
							</button>
						{:else}
							<p class="text-sm text-base-content/50">No more posts</p>
						{/if}
					</div>
				{:else if !error}
					<div class="rounded-xl border border-base-300 bg-base-100 p-8 text-center text-base-content/60">
						No posts for this realm with current filters.
					</div>
				{/if}
			</section>
		</div>
	</div>
{/if}

// app/pages/realms/[slug].vue
<template>
  <div>
    <!-- Invite Variant: Centered Card -->
    <div v-if="isInviteMode">
      <div
        class="fixed inset-0 transition-all duration-500"
        :style="pageStyle"
      />

      <div
        class="relative flex items-center justify-center min-h-layout overflow-auto p-4"
      >
        <n-card
          :class="[
            'w-full',
            'max-w-[480px]',
            { 'backdrop-blur-2xl': realmBackground },
            { 'shadow-xl': realmBackground }
          ]"
          size="large"
          :style="
            realmBackground ? 'background-color: rgba(255, 255, 255, 0.1)' : ''
          "
          :content-style="
            realmBackground ? 'background-color: transparent' : ''
          "
        >
          <div v-if="realm" class="p-4">
            <div class="flex flex-col items-center text-center">
              <n-avatar :src="realmPicture" :size="80" class="mb-4">
                <n-icon v-if="!realmPicture" :component="Users" :size="40" />
              </n-avatar>

              <div class="flex gap-2 items-center">
                <h2 class="text-2xl font-bold mb-2">{{ realm.name }}</h2>
                <verification-mark
                  v-if="realm.verification"
                  :mark="realm.verification"
                  :size="20"
                />
              </div>
              <p v-if="realm.description" class="text-base mb-4 opacity-80">
                {{ realm.description }}
              </p>

              <div class="flex gap-2 mb-6">
                <n-tag :bordered="false" type="info">
                  {{ realm.isCommunity ? "Community" : "Organization" }}
                </n-tag>
                <n-tag
                  :bordered="false"
                  :type="realm.isPublic ? 'success' : 'warning'"
                >
                  {{ realm.isPublic ? "Public" : "Private" }}
                </n-tag>
              </div>

              <n-card
                v-if="realm.verification"
                class="text-left mb-4 w-full"
                :style="
                  realmBackground
                    ? 'background-color: rgba(255, 255, 255, 0.1)'
                    : ''
                "
                :content-style="
                  realmBackground ? 'background-color: transparent' : ''
                "
              >
                <verification-status-card :mark="realm.verification" />
              </n-card>

              <n-button
                text-color="white"
                type="primary"
                block
                size="large"
                :loading="isJoining"
                :disabled="isMember"
                @click="handleJoin"
              >
                <template #icon>
                  <n-icon :component="UserPlus" />
                </template>
                Join Realm
              </n-button>

              <n-alert
                v-if="isMember"
                type="info"
                title="Already Joined"
                class="mt-4"
              >
                You already joined this realm,
                <nuxt-link
                  :to="`/realms/${route.params.slug}`"
                  class="underline font-bold"
                >
                  go to the realm page instead.
                </nuxt-link>
              </n-alert>
            </div>
          </div>
          <div v-else-if="notFound" class="flex justify-center p-8">
            <n-empty description="Realm not found">
              <template #icon>
                <n-icon :component="Users" />
              </template>
            </n-empty>
          </div>
          <div v-else class="flex justify-center p-8">
            <n-spin size="large" />
          </div>
        </n-card>
      </div>
    </div>

    <!-- Regular View: Full Realm Page -->
    <div v-else>
      <div class="fixed inset-0 blur-md" :style="pageStyle" />
      <img
        :src="realmBackground"
        class="w-full max-h-48 object-cover object-top"
        :style="{ aspectRatio: '16/7', opacity: headerOpacity }"
      />
      <div v-if="realm" class="relative min-h-layout">
        <div class="container mx-auto p-4 sm:p-8">
          <div class="layout">
            <div class="sidebar flex flex-col gap-3">
              <n-card
                :class="cardClass"
                :style="cardStyle"
                :content-style="cardContentStyle"
              >
                <div class="flex items-center gap-4 mb-4">
                  <n-avatar size="large" round :src="realmPicture">
                    <n-icon
                      v-if="!realmPicture"
                      :component="Users"
                      :size="28"
                    />
                  </n-avatar>
                  <div>
                    <div class="flex gap-2 items-center">
                      <div class="text-xl font-bold">
                        {{ realm.name }}
                      </div>
                      <verification-mark
                        v-if="realm.verification"
                        :mark="realm.verification"
                      />
                    </div>

                    <div class="text-sm opacity-80">@{{ realm.slug }}</div>
                  </div>
                </div>
                <p v-if="realm.description" class="text-sm mb-4">
                  {{ realm.description }}
                </p>
                <div class="flex flex-wrap gap-2">
                  <n-tag :bordered="false" type="info">
                    {{ realm.isCommunity ? "Community" : "Organization" }}
                  </n-tag>
                  <n-tag
                    :bordered="false"
                    :type="realm.isPublic ? 'success' : 'warning'"
                  >
                    {{ realm.isPublic ? "Public" : "Private" }}
                  </n-tag>
                </div>
              </n-card>

              <n-card
                v-if="realm.verification"
                :class="cardClass"
                :style="cardStyle"
                :content-style="cardContentStyle"
              >
                <verification-status-card :mark="realm.verification" />
              </n-card>

              <div v-if="realm.isPublic && !isMember">
                <n-button
                  type="primary"
                  block
                  size="large"
                  :loading="isJoining"
                  @click="handleJoin"
                >
                  <template #icon>
                    <n-icon :component="UserPlus" />
                  </template>
                  Join Realm
                </n-button>
              </div>
            </div>
            <div class="main">
              <!-- Filter Section -->
              <n-card
                class="mb-4"
                :class="cardClass"
                :style="cardStyle"
                :content-style="cardContentStyle"
              >
                <n-tabs v-model:value="activeCategoryTab" type="segment">
                  <n-tab name="all">All</n-tab>
                  <n-tab name="posts">Posts</n-tab>
                  <n-tab name="articles">Articles</n-tab>
                </n-tabs>

                <div class="mx-4">
                  <div
                    class="grid grid-cols-1 sm:grid-cols-2 gap-x-4 gap-y-2 mt-4"
                  >
                    <div
                      class="flex items-center gap-2 cursor-pointer"
                      @click="cycleIncludeReplies"
                    >
                      <n-icon :component="Reply" />
                      <n-checkbox
                        :checked="includeReplies !== false"
                        :indeterminate="includeReplies === null"
                        @update:checked="cycleIncludeReplies"
                      >
                        Include replies
                      </n-checkbox>
                    </div>
                    <div class="flex items-center gap-2">
                      <n-icon :component="Paperclip" />
                      <n-checkbox v-model:checked="mediaOnly">
                        Media only
                      </n-checkbox>
                    </div>
                    <div class="flex items-center gap-2">
                      <n-icon :component="ArrowUpDown" />
                      <n-checkbox v-model:checked="orderDesc">
                        Descending order
                      </n-checkbox>
                    </div>
                  </div>

                  <div
                    class="flex items-center cursor-pointer mt-4"
                    @click="showAdvancedFilters = !showAdvancedFilters"
                  >
                    <n-icon :component="Filter" />
                    <span class="ml-2 font-medium">Advanced filters</span>
                    <n-icon class="ml-auto">
                      <ChevronDown v-if="!showAdvancedFilters" />
                      <ChevronUp v-else />
                    </n-icon>
                  </div>

                  <n-collapse-transition :show="showAdvancedFilters">
                    <div class="mt-4 flex flex-col gap-3">
                      <n-input
                        v-model:value="queryTerm"
                        placeholder="Search posts"
                      >
                        <template #prefix>
                          <n-icon :component="Search" />
                        </template>
                      </n-input>

                      <n-config-provider
                        :theme-overrides="{ common: { borderRadius: '8px' } }"
                      >
                        <n-select
                          v-model:value="order"
                          placeholder="Sort by"
                          :options="[
                            { label: 'Date', value: 'date' },
                            { label: 'Popularity', value: 'popularity' }
                          ]"
                        />
                      </n-config-provider>

                      <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
                        <n-date-picker
                          v-model:value="periodStart"
                          type="date"
                          placeholder="From date"
                          clearable
                        />
                        <n-date-picker
                          v-model:value="periodEnd"
                          type="date"
                          placeholder="To date"
                          clearable
                        />
                      </div>
                    </div>
                  </n-collapse-transition>
                </div>
              </n-card>

              <post-list :key="filterKey" :params="postListParams" />
            </div>
          </div>
        </div>
      </div>
      <div
        v-else-if="notFound"
        class="relative flex justify-center items-center h-full"
      >
        <n-empty description="The realm you're trying to access is not found.">
          <template #icon>
            <n-icon :component="Users" />
          </template>
        </n-empty>
      </div>
      <div v-else class="relative flex justify-center items-center h-full">
        <n-spin size="large" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from "vue"
import { useWindowScroll } from "@vueuse/core"
import { useMarkdownProcessor } from "~/composables/useMarkdownProcessor"
import type { SnRealm } from "~/types/api"
import type { PostListParams } from "~/composables/usePostList"
import PostList from "~/components/Post/PostList.vue"
import {
  Reply,
  Paperclip,
  ArrowUpDown,
  Filter,
  Search,
  ChevronDown,
  ChevronUp,
  Users,
  UserPlus
} from "lucide-vue-next"

const route = useRoute()
const message = useMessage()
const api = useSolarNetwork()

const notFound = ref<boolean>(false)
const realm = ref<SnRealm | null>(null)
const isJoining = ref(false)
const isMember = ref(false)
const checkingMembership = ref(false)

// Check if we're in invite mode
const isInviteMode = computed(() => {
  return !!route.query.invite
})

// Use useFetch with the correct API URL to avoid router conflicts
const apiBase = useSolarNetworkUrl()
const apiBaseServer = useSolarNetworkUrl()

try {
  const { data, error } = await useFetch<SnRealm>(
    `${apiBaseServer}/pass/realms/${route.params.slug}`,
    { server: true }
  )

  if (error.value) {
    console.error("Failed to fetch realm:", error.value)
    notFound.value = true
  } else if (data.value) {
    realm.value = keysToCamel(data.value)
  }
} catch (err) {
  console.error("Failed to fetch realm:", err)
  notFound.value = true
}

const realmBackground = computed(() => {
  return realm.value?.background
    ? `${apiBase}/drive/files/${realm.value.background.id}?original=true`
    : undefined
})
const realmPicture = computed(() => {
  return realm.value?.picture
    ? `${apiBase}/drive/files/${realm.value.picture.id}`
    : undefined
})

const { y: scrollY } = useWindowScroll()
const scrollThreshold = 192 // max-h-48 is 12rem = 192px

const backgroundOpacity = computed(() => {
  return Math.max(0, Math.min(scrollY.value / scrollThreshold, 1))
})

const headerOpacity = computed(() => {
  return 1 - backgroundOpacity.value
})

const pageStyle = computed(() => {
  if (!realmBackground.value) return {}
  return {
    backgroundImage: `linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), url('${realmBackground.value}')`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    backgroundAttachment: "fixed",
    opacity: isInviteMode.value ? 1 : backgroundOpacity.value
  }
})

const cardClass = computed(() => ({
  "backdrop-blur-2xl": !!realmBackground.value,
  "shadow-xl": !!realmBackground.value
}))

const cardStyle = computed(() =>
  realmBackground.value
    ? "background-color: var(--n-color-modal)"
    : "background-color: var(--n-color)"
)

const cardContentStyle = computed(() =>
  realmBackground.value ? "background-color: transparent" : ""
)

// Filter state
const activeCategoryTab = ref("all")
const includeReplies = ref<boolean | null>(null)
const mediaOnly = ref(false)
const orderDesc = ref(true)
const showAdvancedFilters = ref(false)
const queryTerm = ref("")
const order = ref<string | null>(null)
const periodStart = ref<number | null>(null)
const periodEnd = ref<number | null>(null)

const postListParams = computed<PostListParams>(() => {
  const params: PostListParams = {
    realm: route.params.slug as string,
    includeReplies: includeReplies.value ?? undefined,
    mediaOnly: mediaOnly.value,
    orderDesc: orderDesc.value,
    queryTerm: queryTerm.value || undefined,
    order: order.value ?? undefined,
    periodStart: periodStart.value
      ? Math.floor(periodStart.value / 1000)
      : undefined,
    periodEnd: periodEnd.value ? Math.floor(periodEnd.value / 1000) : undefined
  }

  if (activeCategoryTab.value === "posts") {
    params.type = 0
  } else if (activeCategoryTab.value === "articles") {
    params.type = 1
  }

  return params
})

const filterKey = computed(() => {
  return JSON.stringify(postListParams.value)
})

const cycleIncludeReplies = () => {
  if (includeReplies.value === null) {
    includeReplies.value = true
  } else if (includeReplies.value === true) {
    includeReplies.value = false
  } else {
    includeReplies.value = null
  }
}

// Check membership status
async function checkMembership() {
  if (!realm.value) return

  checkingMembership.value = true
  try {
    await api(`/pass/realms/${realm.value.slug}/members/me`, {
      method: "GET"
    })
    isMember.value = true
  } catch (err) {
    // 404 means not a member
    isMember.value = false
  } finally {
    checkingMembership.value = false
  }
}

// Handle join realm
async function handleJoin() {
  if (!realm.value) return

  isJoining.value = true
  try {
    await api(`/pass/realms/${realm.value.slug}/members/me`, {
      method: "POST"
    })
    message.success(`Successfully joined ${realm.value.name}!`)
    isMember.value = true
    // Redirect to the realm page without invite query if in invite mode
    if (isInviteMode.value) {
      await navigateTo(`/realms/${realm.value.slug}`)
    }
  } catch (err) {
    message.error(err instanceof Error ? err.message : String(err))
  } finally {
    isJoining.value = false
  }
}

// Check membership on mount
onMounted(() => {
  if (realm.value) {
    checkMembership()
  }
})

definePageMeta({
  title: "Realms",
  alias: ["/r/:slug()"]
})

useHead({
  title: computed(() => {
    if (notFound.value) {
      return "Realm not found"
    }
    if (realm.value) {
      return realm.value.name
    }
    return "Loading realm..."
  }),
  meta: computed(() => {
    if (realm.value) {
      const description =
        realm.value.description || `Join ${realm.value.name} on Solar Network.`
      return [{ name: "description", content: description }]
    }
    return []
  })
})

defineOgImage({
  component: "ImageCard",
  // @ts-ignore
  title: computed(() => (realm.value ? realm.value.name : "Realm")),
  description: computed(() =>
    realm.value
      ? realm.value.description || `Join ${realm.value.name} on Solar Network.`
      : ""
  ),
  avatarUrl: computed(() => realmPicture.value),
  backgroundImage: computed(() => realmBackground.value)
})
</script>

<style scoped>
.layout {
  display: grid;
  grid-template-columns: 1fr;
  gap: 16px;
}

.main {
  order: 2;
  min-width: 0;
}

.sidebar {
  order: 1;
  height: auto;
}

@media (min-width: 960px) {
  .layout {
    grid-template-columns: 1fr 2fr;
  }

  .main {
    order: unset;
  }

  .sidebar {
    order: unset;
  }
}

@media (min-width: 1280px) {
  .sidebar {
    position: sticky;
    top: calc(var(--header-height) + 8px);
    align-self: start;
  }
}
</style>
