// app/pages/orders/[id].vue
<template>
  <div class="flex items-center justify-center min-h-screen">
    <n-card title="Order Payment" class="max-w-sm">
      <template #header-icon>
        <n-icon :component="Wallet" />
      </template>
      <n-alert v-if="done" type="success" class="mb-4">
        The order has been paid successfully. You can now close this tab and
        return to Solar Network!
      </n-alert>
      <n-alert
        v-else-if="!!error"
        type="error"
        title="Something went wrong"
        class="mb-4"
      >
        {{ error }}
      </n-alert>
      <div v-else-if="!!order" class="flex flex-col gap-2">
        <p>Order for {{ order.productIdentifier ?? "unknown" }}</p>
        <div class="flex items-center gap-2">
          <n-icon :component="Tag" />
          <strong>{{ order.remarks }}</strong>
        </div>
        <div class="flex items-center gap-2">
          <n-icon :component="CircleDollarSign" />
          <span>Amount</span>
          <strong>{{ order.amount }} {{ order.currency }}</strong>
        </div>
        <div v-if="order.expiredAt" class="flex items-center gap-2">
          <n-icon :component="Calendar" />
          <span>Until</span>
          <strong>{{ new Date(order.expiredAt).toLocaleString() }}</strong>
        </div>
        <div class="mt-4">
          <n-input
            v-model:value="pinCode"
            type="password"
            show-password-on="click"
            placeholder="6-digit PIN"
            maxlength="6"
            :input-props="{ autocomplete: 'one-time-code' }"
          />
          <n-button
            type="primary"
            :loading="submitting"
            class="mt-4 w-full"
            @click="pay"
          >
            <template #icon>
              <n-icon :component="Check" />
            </template>
            Pay
          </n-button>
        </div>
      </div>
      <div v-else class="flex justify-center p-8">
        <n-spin size="medium" />
      </div>
    </n-card>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue"
import { useRoute } from "vue-router"
import type { SnWalletOrder } from "~/types/api/order"
import {
  Wallet,
  Tag,
  CircleDollarSign,
  Calendar,
  Check
} from "lucide-vue-next"

const route = useRoute()

const orderId: string =
  typeof route.params.id === "string"
    ? route.params.id
    : route.params.id?.join("/") || ""
const order = ref<SnWalletOrder | null>(null)
const error = ref<string | null>(null)

const pinCode = ref<string>()

const submitting = ref(false)
const done = ref(false)

const api = useSolarNetwork()

async function fetchOrder() {
  try {
    const resp = await api<SnWalletOrder>(
      `/id/orders/${encodeURIComponent(orderId)}`
    )
    order.value = resp
  } catch (err: unknown) {
    error.value = err instanceof Error ? err.message : String(err)
  }
}

async function pay() {
  if (submitting.value) return
  submitting.value = true
  try {
    await api(`/id/orders/${encodeURIComponent(orderId)}/pay`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ pin_code: pinCode.value })
    })
    done.value = true
  } catch (err: unknown) {
    error.value = err instanceof Error ? err.message : String(err)
  } finally {
    submitting.value = false
  }
}

onMounted(() => fetchOrder())

definePageMeta({
  middleware: ["auth"],
  title: "Solarpay"
})
</script>

// src/routes/(flow)/orders/[id]/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { onMount } from 'svelte';
	import { Wallet, Tag, CircleDollarSign, Calendar, Check } from 'lucide-svelte';
	import { getOrder, payOrder, type WalletOrder } from '$lib/utils/api';

	let order = $state<WalletOrder | null>(null);
	let error = $state<string | null>(null);
	let pinCode = $state('');
	let submitting = $state(false);
	let done = $state(false);
	let loading = $state(true);

	const orderId = $derived($page.params.id ?? '');

	async function fetchOrder() {
		if (!orderId) {
			error = 'Invalid order id';
			loading = false;
			return;
		}
		loading = true;
		error = null;
		try {
			order = await getOrder(orderId);
		} catch (err) {
			error = err instanceof Error ? err.message : String(err);
		} finally {
			loading = false;
		}
	}

	async function pay() {
		if (submitting || pinCode.length !== 6 || !orderId) return;
		submitting = true;
		error = null;
		try {
			await payOrder(orderId, pinCode);
			done = true;
		} catch (err) {
			error = err instanceof Error ? err.message : String(err);
		} finally {
			submitting = false;
		}
	}

	onMount(fetchOrder);
</script>

<svelte:head>
	<title>Order Payment - Solar Network</title>
</svelte:head>

<div class="w-full max-w-md">
	<div class="card/90 shadow-xl backdrop-blur">
		<div class="card-body">
			<div class="mb-2 flex items-center gap-2">
				<Wallet class="text-primary" size={18} />
				<h1 class="text-lg font-bold">Order Payment</h1>
			</div>

			{#if done}
				<div class="alert alert-success">
					<span>The order has been paid successfully. You can close this tab now.</span>
				</div>
			{:else if error}
				<div class="alert alert-error">
					<span>{error}</span>
				</div>
			{:else if loading}
				<div class="flex justify-center py-8">
					<span class="loading loading-md loading-spinner"></span>
				</div>
			{:else if order}
				<div class="space-y-3 text-sm">
					<p>Order for {order.productIdentifier ?? 'unknown'}</p>
					<div class="flex items-center gap-2">
						<Tag size={16} />
						<strong>{order.remarks || 'No remarks'}</strong>
					</div>
					<div class="flex items-center gap-2">
						<CircleDollarSign size={16} />
						<span>Amount</span>
						<strong>{order.amount} {order.currency}</strong>
					</div>
					{#if order.expiredAt}
						<div class="flex items-center gap-2">
							<Calendar size={16} />
							<span>Until</span>
							<strong>{new Date(order.expiredAt).toLocaleString()}</strong>
						</div>
					{/if}
				</div>

				<div class="mt-4">
					<input
						class="input-bordered input w-full"
						type="password"
						placeholder="6-digit PIN"
						maxlength="6"
						inputmode="numeric"
						autocomplete="one-time-code"
						bind:value={pinCode}
					/>
					<button
						class="btn mt-4 w-full btn-primary"
						onclick={pay}
						disabled={submitting || pinCode.length !== 6}
					>
						{#if submitting}
							<span class="loading loading-sm loading-spinner"></span>
						{:else}
							<Check size={16} />
						{/if}
						Pay
					</button>
				</div>
			{/if}
		</div>
	</div>
</div>
